TRUNCATE TABLE Country;

INSERT INTO Country(ISO3166, name) VALUES ('AU','Австралія');
INSERT INTO Country(ISO3166, name) VALUES ('AT','Австрія');
INSERT INTO Country(ISO3166, name) VALUES ('AZ','Азербайджан');
INSERT INTO Country(ISO3166, name) VALUES ('AX','Аландські острови');
INSERT INTO Country(ISO3166, name) VALUES ('AL','Албанія');
INSERT INTO Country(ISO3166, name) VALUES ('DZ','Алжир');
INSERT INTO Country(ISO3166, name) VALUES ('AS','Американське Самоа');
INSERT INTO Country(ISO3166, name) VALUES ('AI','Ангілья');
INSERT INTO Country(ISO3166, name) VALUES ('AO','Ангола');
INSERT INTO Country(ISO3166, name) VALUES ('AD','Андорра');
INSERT INTO Country(ISO3166, name) VALUES ('AQ','Антарктика');
INSERT INTO Country(ISO3166, name) VALUES ('AG','Антигуа і Барбуда');
INSERT INTO Country(ISO3166, name) VALUES ('AR','Аргентина');
INSERT INTO Country(ISO3166, name) VALUES ('AW','Аруба');
INSERT INTO Country(ISO3166, name) VALUES ('AF','Афганістан');
INSERT INTO Country(ISO3166, name) VALUES ('BS','Багами');
INSERT INTO Country(ISO3166, name) VALUES ('BD','Бангладеш');
INSERT INTO Country(ISO3166, name) VALUES ('BB','Барбадос');
INSERT INTO Country(ISO3166, name) VALUES ('BH','Бахрейн');
INSERT INTO Country(ISO3166, name) VALUES ('BZ','Беліз');
INSERT INTO Country(ISO3166, name) VALUES ('BE','Бельгія');
INSERT INTO Country(ISO3166, name) VALUES ('BJ','Бенін');
INSERT INTO Country(ISO3166, name) VALUES ('BM','Бермуди');
INSERT INTO Country(ISO3166, name) VALUES ('BY','Білорусь');
INSERT INTO Country(ISO3166, name) VALUES ('BG','Болгарія');
INSERT INTO Country(ISO3166, name) VALUES ('BO','Болівія');
INSERT INTO Country(ISO3166, name) VALUES ('BA','Боснія і Герцоговина');
INSERT INTO Country(ISO3166, name) VALUES ('BW','Ботсвана');
INSERT INTO Country(ISO3166, name) VALUES ('BR','Бразилія');
INSERT INTO Country(ISO3166, name) VALUES ('VG','Британські Віргінські острови');
INSERT INTO Country(ISO3166, name) VALUES ('BN','Бруней');
INSERT INTO Country(ISO3166, name) VALUES ('BF','Буркіна-Фасо');
INSERT INTO Country(ISO3166, name) VALUES ('BI','Бурунді');
INSERT INTO Country(ISO3166, name) VALUES ('BT','Бутан');
INSERT INTO Country(ISO3166, name) VALUES ('VU','Вануату');
INSERT INTO Country(ISO3166, name) VALUES ('VA','Ватикан');
INSERT INTO Country(ISO3166, name) VALUES ('GB','Велика Британія');
INSERT INTO Country(ISO3166, name) VALUES ('VE','Венесуела');
INSERT INTO Country(ISO3166, name) VALUES ('UM','Віддалені острови США');
INSERT INTO Country(ISO3166, name) VALUES ('VI','Віргінські острови, США');
INSERT INTO Country(ISO3166, name) VALUES ('AM','Вірменія');
INSERT INTO Country(ISO3166, name) VALUES ('WF','Волліс і Футуна');
INSERT INTO Country(ISO3166, name) VALUES ('VN','В?єтнам');
INSERT INTO Country(ISO3166, name) VALUES ('GA','Габон');
INSERT INTO Country(ISO3166, name) VALUES ('HT','Гаїті');
INSERT INTO Country(ISO3166, name) VALUES ('GM','Гамбія');
INSERT INTO Country(ISO3166, name) VALUES ('GH','Гана');
INSERT INTO Country(ISO3166, name) VALUES ('GY','Гаяна');
INSERT INTO Country(ISO3166, name) VALUES ('GP','Гваделупа');
INSERT INTO Country(ISO3166, name) VALUES ('GT','Гватемала');
INSERT INTO Country(ISO3166, name) VALUES ('GN','Гвінея');
INSERT INTO Country(ISO3166, name) VALUES ('GW','Гвінея-Бісау');
INSERT INTO Country(ISO3166, name) VALUES ('GG','Гернсі');
INSERT INTO Country(ISO3166, name) VALUES ('GI','Гібралтар');
INSERT INTO Country(ISO3166, name) VALUES ('HN','Гондурас');
INSERT INTO Country(ISO3166, name) VALUES ('HK','Гонконг, О.А.Р. Китаю');
INSERT INTO Country(ISO3166, name) VALUES ('GD','Гренада');
INSERT INTO Country(ISO3166, name) VALUES ('GL','Гренландія');
INSERT INTO Country(ISO3166, name) VALUES ('GR','Греція');
INSERT INTO Country(ISO3166, name) VALUES ('GE','Грузія');
INSERT INTO Country(ISO3166, name) VALUES ('GU','Гуам');
INSERT INTO Country(ISO3166, name) VALUES ('DK','Данія');
INSERT INTO Country(ISO3166, name) VALUES ('JE','Джерсі');
INSERT INTO Country(ISO3166, name) VALUES ('DJ','Джибуті');
INSERT INTO Country(ISO3166, name) VALUES ('DG','Дієго-Гарсія');
INSERT INTO Country(ISO3166, name) VALUES ('DM','Домініка');
INSERT INTO Country(ISO3166, name) VALUES ('DO','Домініканська Республіка');
INSERT INTO Country(ISO3166, name) VALUES ('EC','Еквадор');
INSERT INTO Country(ISO3166, name) VALUES ('GQ','Екваторіальна Гвінея');
INSERT INTO Country(ISO3166, name) VALUES ('ER','Еритрея');
INSERT INTO Country(ISO3166, name) VALUES ('EE','Естонія');
INSERT INTO Country(ISO3166, name) VALUES ('ET','Ефіопія');
INSERT INTO Country(ISO3166, name) VALUES ('EG','Єгипет');
INSERT INTO Country(ISO3166, name) VALUES ('YE','Ємен');
INSERT INTO Country(ISO3166, name) VALUES ('ZM','Замбія');
INSERT INTO Country(ISO3166, name) VALUES ('EH','Західна Сахара');
INSERT INTO Country(ISO3166, name) VALUES ('ZW','Зімбабве');
INSERT INTO Country(ISO3166, name) VALUES ('IL','Ізраїль');
INSERT INTO Country(ISO3166, name) VALUES ('IN','Індія');
INSERT INTO Country(ISO3166, name) VALUES ('ID','Індонезія');
INSERT INTO Country(ISO3166, name) VALUES ('IQ','Ірак');
INSERT INTO Country(ISO3166, name) VALUES ('IR','Іран');
INSERT INTO Country(ISO3166, name) VALUES ('IE','Ірландія');
INSERT INTO Country(ISO3166, name) VALUES ('IS','Ісландія');
INSERT INTO Country(ISO3166, name) VALUES ('ES','Іспанія');
INSERT INTO Country(ISO3166, name) VALUES ('IT','Італія');
INSERT INTO Country(ISO3166, name) VALUES ('JO','Йорданія');
INSERT INTO Country(ISO3166, name) VALUES ('CV','Кабо Верде');
INSERT INTO Country(ISO3166, name) VALUES ('KZ','Казахстан');
INSERT INTO Country(ISO3166, name) VALUES ('KY','Кайманові острови');
INSERT INTO Country(ISO3166, name) VALUES ('KH','Камбоджа');
INSERT INTO Country(ISO3166, name) VALUES ('CM','Камерун');
INSERT INTO Country(ISO3166, name) VALUES ('CA','Канада');
INSERT INTO Country(ISO3166, name) VALUES ('IC','Канарські острови');
INSERT INTO Country(ISO3166, name) VALUES ('QA','Катар');
INSERT INTO Country(ISO3166, name) VALUES ('KE','Кенія');
INSERT INTO Country(ISO3166, name) VALUES ('KG','Киргизстан');
INSERT INTO Country(ISO3166, name) VALUES ('CN','Китай');
INSERT INTO Country(ISO3166, name) VALUES ('CY','Кіпр');
INSERT INTO Country(ISO3166, name) VALUES ('KI','Кірибаті');
INSERT INTO Country(ISO3166, name) VALUES ('CC','Кокосові (Кілінгові) острови');
INSERT INTO Country(ISO3166, name) VALUES ('CO','Колумбія');
INSERT INTO Country(ISO3166, name) VALUES ('KM','Коморські острови');
INSERT INTO Country(ISO3166, name) VALUES ('CG','Конго – Браззавіль');
INSERT INTO Country(ISO3166, name) VALUES ('CD','Конго – Кіншаса');
INSERT INTO Country(ISO3166, name) VALUES ('XK','Косово');
INSERT INTO Country(ISO3166, name) VALUES ('CR','Коста-Рика');
INSERT INTO Country(ISO3166, name) VALUES ('CI','Кот-д’Івуар');
INSERT INTO Country(ISO3166, name) VALUES ('CU','Куба');
INSERT INTO Country(ISO3166, name) VALUES ('KW','Кувейт');
INSERT INTO Country(ISO3166, name) VALUES ('CW','Кюрасао');
INSERT INTO Country(ISO3166, name) VALUES ('LA','Лаос');
INSERT INTO Country(ISO3166, name) VALUES ('LV','Латвія');
INSERT INTO Country(ISO3166, name) VALUES ('LS','Лесото');
INSERT INTO Country(ISO3166, name) VALUES ('LT','Литва');
INSERT INTO Country(ISO3166, name) VALUES ('LR','Ліберія');
INSERT INTO Country(ISO3166, name) VALUES ('LB','Ліван');
INSERT INTO Country(ISO3166, name) VALUES ('LY','Лівія');
INSERT INTO Country(ISO3166, name) VALUES ('LI','Ліхтенштейн');
INSERT INTO Country(ISO3166, name) VALUES ('LU','Люксембург');
INSERT INTO Country(ISO3166, name) VALUES ('MU','Маврикій');
INSERT INTO Country(ISO3166, name) VALUES ('MR','Мавританія');
INSERT INTO Country(ISO3166, name) VALUES ('MG','Мадагаскар');
INSERT INTO Country(ISO3166, name) VALUES ('YT','Майотта');
INSERT INTO Country(ISO3166, name) VALUES ('MO','Макао О.А.Р. Китаю');
INSERT INTO Country(ISO3166, name) VALUES ('MK','Македонія');
INSERT INTO Country(ISO3166, name) VALUES ('MW','Малаві');
INSERT INTO Country(ISO3166, name) VALUES ('MY','Малайзія');
INSERT INTO Country(ISO3166, name) VALUES ('ML','Малі');
INSERT INTO Country(ISO3166, name) VALUES ('MV','Мальдіви');
INSERT INTO Country(ISO3166, name) VALUES ('MT','Мальта');
INSERT INTO Country(ISO3166, name) VALUES ('MA','Марокко');
INSERT INTO Country(ISO3166, name) VALUES ('MQ','Мартиніка');
INSERT INTO Country(ISO3166, name) VALUES ('MH','Маршаллові Острови');
INSERT INTO Country(ISO3166, name) VALUES ('MX','Мексика');
INSERT INTO Country(ISO3166, name) VALUES ('FM','Мікронезія');
INSERT INTO Country(ISO3166, name) VALUES ('MZ','Мозамбік');
INSERT INTO Country(ISO3166, name) VALUES ('MD','Молдова');
INSERT INTO Country(ISO3166, name) VALUES ('MC','Монако');
INSERT INTO Country(ISO3166, name) VALUES ('MN','Монголія');
INSERT INTO Country(ISO3166, name) VALUES ('MS','Монтсеррат');
INSERT INTO Country(ISO3166, name) VALUES ('MM','М''янма (Бірма)');
INSERT INTO Country(ISO3166, name) VALUES ('NA','Намібія');
INSERT INTO Country(ISO3166, name) VALUES ('NR','Науру');
INSERT INTO Country(ISO3166, name) VALUES ('NP','Непал');
INSERT INTO Country(ISO3166, name) VALUES ('NE','Нігер');
INSERT INTO Country(ISO3166, name) VALUES ('NG','Нігерія');
INSERT INTO Country(ISO3166, name) VALUES ('NL','Нідерланди');
INSERT INTO Country(ISO3166, name) VALUES ('BQ','Нідерландські Карибські острови');
INSERT INTO Country(ISO3166, name) VALUES ('NI','Нікарагуа');
INSERT INTO Country(ISO3166, name) VALUES ('DE','Німеччина');
INSERT INTO Country(ISO3166, name) VALUES ('NU','Ніуе');
INSERT INTO Country(ISO3166, name) VALUES ('NZ','Нова Зеландія');
INSERT INTO Country(ISO3166, name) VALUES ('NC','Нова Каледонія');
INSERT INTO Country(ISO3166, name) VALUES ('NO','Норвегія');
INSERT INTO Country(ISO3166, name) VALUES ('AE','Об''єднані Арабські Емірати');
INSERT INTO Country(ISO3166, name) VALUES ('OM','Оман');
INSERT INTO Country(ISO3166, name) VALUES ('AC','Острів Вознесіння');
INSERT INTO Country(ISO3166, name) VALUES ('IM','Острів Мен');
INSERT INTO Country(ISO3166, name) VALUES ('NF','Острів Норфолк');
INSERT INTO Country(ISO3166, name) VALUES ('CX','Острів Різдва');
INSERT INTO Country(ISO3166, name) VALUES ('SH','Острів Святої Єлени');
INSERT INTO Country(ISO3166, name) VALUES ('CK','Острови Кука');
INSERT INTO Country(ISO3166, name) VALUES ('PN','Острови Піткерн');
INSERT INTO Country(ISO3166, name) VALUES ('SJ','Острови Свальбард і Ян-Маєн');
INSERT INTO Country(ISO3166, name) VALUES ('TC','Острови Теркс і Кайкос');
INSERT INTO Country(ISO3166, name) VALUES ('PK','Пакистан');
INSERT INTO Country(ISO3166, name) VALUES ('PW','Палау');
INSERT INTO Country(ISO3166, name) VALUES ('PS','Палестинські території');
INSERT INTO Country(ISO3166, name) VALUES ('PA','Панама');
INSERT INTO Country(ISO3166, name) VALUES ('PG','Папуа Нова Гвінея');
INSERT INTO Country(ISO3166, name) VALUES ('ZA','ПАР');
INSERT INTO Country(ISO3166, name) VALUES ('PY','Парагвай');
INSERT INTO Country(ISO3166, name) VALUES ('PE','Перу');
INSERT INTO Country(ISO3166, name) VALUES ('KR','Південна Корея');
INSERT INTO Country(ISO3166, name) VALUES ('SS','Південний Судан');
INSERT INTO Country(ISO3166, name) VALUES ('KP','Північна Корея');
INSERT INTO Country(ISO3166, name) VALUES ('MP','Північні Маріанські острови');
INSERT INTO Country(ISO3166, name) VALUES ('PL','Польща');
INSERT INTO Country(ISO3166, name) VALUES ('PT','Португалія');
INSERT INTO Country(ISO3166, name) VALUES ('PR','Пуерто-Рико');
INSERT INTO Country(ISO3166, name) VALUES ('RE','Реюньйон');
INSERT INTO Country(ISO3166, name) VALUES ('RU','Росія');
INSERT INTO Country(ISO3166, name) VALUES ('RW','Руанда');
INSERT INTO Country(ISO3166, name) VALUES ('RO','Румунія');
INSERT INTO Country(ISO3166, name) VALUES ('SV','Сальвадор');
INSERT INTO Country(ISO3166, name) VALUES ('WS','Самоа');
INSERT INTO Country(ISO3166, name) VALUES ('SM','Сан-Марино');
INSERT INTO Country(ISO3166, name) VALUES ('ST','Сан-Томе і Прінсіпі');
INSERT INTO Country(ISO3166, name) VALUES ('SA','Саудівська Аравія');
INSERT INTO Country(ISO3166, name) VALUES ('SZ','Свазіленд');
INSERT INTO Country(ISO3166, name) VALUES ('SC','Сейшельські острови');
INSERT INTO Country(ISO3166, name) VALUES ('BL','Сен-Бартельмі');
INSERT INTO Country(ISO3166, name) VALUES ('MF','Сен-Мартен');
INSERT INTO Country(ISO3166, name) VALUES ('PM','Сен-П''єр і Мікелон');
INSERT INTO Country(ISO3166, name) VALUES ('SN','Сенегал');
INSERT INTO Country(ISO3166, name) VALUES ('VC','Сент-Вінсент і Гренадини');
INSERT INTO Country(ISO3166, name) VALUES ('KN','Сент-Кітс і Невіс');
INSERT INTO Country(ISO3166, name) VALUES ('LC','Сент-Люсія');
INSERT INTO Country(ISO3166, name) VALUES ('RS','Сербія');
INSERT INTO Country(ISO3166, name) VALUES ('EA','Сеута і Мелілья');
INSERT INTO Country(ISO3166, name) VALUES ('SY','Сирія');
INSERT INTO Country(ISO3166, name) VALUES ('SG','Сінгапур');
INSERT INTO Country(ISO3166, name) VALUES ('SX','Сінт-Мартен');
INSERT INTO Country(ISO3166, name) VALUES ('SK','Словаччина');
INSERT INTO Country(ISO3166, name) VALUES ('SI','Словенія');
INSERT INTO Country(ISO3166, name) VALUES ('SB','Соломонові Острови');
INSERT INTO Country(ISO3166, name) VALUES ('SO','Сомалі');
INSERT INTO Country(ISO3166, name) VALUES ('SD','Судан');
INSERT INTO Country(ISO3166, name) VALUES ('SR','Суринам');
INSERT INTO Country(ISO3166, name) VALUES ('TL','Східний Тимор');
INSERT INTO Country(ISO3166, name) VALUES ('US','США');
INSERT INTO Country(ISO3166, name) VALUES ('SL','Сьєрра-Леоне');
INSERT INTO Country(ISO3166, name) VALUES ('TJ','Таджикистан');
INSERT INTO Country(ISO3166, name) VALUES ('TH','Таїланд');
INSERT INTO Country(ISO3166, name) VALUES ('TW','Тайвань');
INSERT INTO Country(ISO3166, name) VALUES ('TZ','Танзанія');
INSERT INTO Country(ISO3166, name) VALUES ('TG','Того');
INSERT INTO Country(ISO3166, name) VALUES ('TK','Токелау');
INSERT INTO Country(ISO3166, name) VALUES ('TO','Тонга');
INSERT INTO Country(ISO3166, name) VALUES ('TT','Тринідад і Тобаго');
INSERT INTO Country(ISO3166, name) VALUES ('TA','Трістан-да-Кунья');
INSERT INTO Country(ISO3166, name) VALUES ('TV','Тувалу');
INSERT INTO Country(ISO3166, name) VALUES ('TN','Туніс');
INSERT INTO Country(ISO3166, name) VALUES ('TR','Туреччина');
INSERT INTO Country(ISO3166, name) VALUES ('TM','Туркменістан');
INSERT INTO Country(ISO3166, name) VALUES ('UG','Уганда');
INSERT INTO Country(ISO3166, name) VALUES ('HU','Угорщина');
INSERT INTO Country(ISO3166, name) VALUES ('UZ','Узбекистан');
INSERT INTO Country(ISO3166, name) VALUES ('UA','Україна');
INSERT INTO Country(ISO3166, name) VALUES ('UY','Уругвай');
INSERT INTO Country(ISO3166, name) VALUES ('FO','Фарерські острови');
INSERT INTO Country(ISO3166, name) VALUES ('FJ','Фіджі');
INSERT INTO Country(ISO3166, name) VALUES ('PH','Філіппіни');
INSERT INTO Country(ISO3166, name) VALUES ('FI','Фінляндія');
INSERT INTO Country(ISO3166, name) VALUES ('FK','Фолклендські острови');
INSERT INTO Country(ISO3166, name) VALUES ('FR','Франція');
INSERT INTO Country(ISO3166, name) VALUES ('GF','Французька Гвіана');
INSERT INTO Country(ISO3166, name) VALUES ('PF','Французька Полінезія');
INSERT INTO Country(ISO3166, name) VALUES ('TF','Французькі Південні Території');
INSERT INTO Country(ISO3166, name) VALUES ('HR','Хорватія');
INSERT INTO Country(ISO3166, name) VALUES ('CF','Центральноафриканська Республіка');
INSERT INTO Country(ISO3166, name) VALUES ('TD','Чад');
INSERT INTO Country(ISO3166, name) VALUES ('CZ','Чехія');
INSERT INTO Country(ISO3166, name) VALUES ('CL','Чилі');
INSERT INTO Country(ISO3166, name) VALUES ('ME','Чорногорія');
INSERT INTO Country(ISO3166, name) VALUES ('CH','Швейцарія');
INSERT INTO Country(ISO3166, name) VALUES ('SE','Швеція');
INSERT INTO Country(ISO3166, name) VALUES ('LK','Шрі-Ланка');
INSERT INTO Country(ISO3166, name) VALUES ('JM','Ямайка');
INSERT INTO Country(ISO3166, name) VALUES ('JP','Японія');