DELETE FROM Region;

INSERT INTO Region (id, name, country_id) VALUES ('1','Вінницька','UA');
INSERT INTO Region (id, name, country_id) VALUES ('2','Волинська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('3','Дніпропетровська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('4','Донецька','UA');
INSERT INTO Region (id, name, country_id) VALUES ('5','Житомирська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('6','Закарпатська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('7','Запорізька','UA');
INSERT INTO Region (id, name, country_id) VALUES ('8','Івано-Франківська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('9','Київ','UA');
INSERT INTO Region (id, name, country_id) VALUES ('10','Київська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('11','Кіровоградська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('12','Луганська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('13','Львівська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('14','Миколаївська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('15','Одеська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('16','Полтавська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('17','Рівненська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('18','Сумська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('19','Тернопільська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('20','Харківська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('21','Херсонська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('22','Хмельницька','UA');
INSERT INTO Region (id, name, country_id) VALUES ('23','Черкаська','UA');
INSERT INTO Region (id, name, country_id) VALUES ('24','Чернівецька','UA');
INSERT INTO Region (id, name, country_id) VALUES ('25','Чернігівська','UA');
