TRUNCATE table City;

INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('33466','UA','1','1',null,'Адамівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('33467','UA','1','1',null,'Антонівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('33468','UA','1','1',null,'Балки');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('35383','UA','2','39',null,'Мельниця');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('35384','UA','2','39',null,'Мирин');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('35385','UA','2','39',null,'Мислина');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('35386','UA','2','39',null,'Мощена');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('35387','UA','2','39',null,'Новий Мосир');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('35388','UA','2','39',null,'Нові Кошари');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50245','UA','16','352',null,'Портнівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50246','UA','16','352',null,'Рожаївка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50247','UA','16','352',null,'Розсошенці');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50248','UA','16','352',null,'Рунівщина');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50249','UA','16','352',null,'Сапожине');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50250','UA','16','352',null,'Сем’янівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50251','UA','16','352',null,'Сердюки');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50252','UA','16','352',null,'Снопове');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50253','UA','16','352',null,'Соломахівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50254','UA','16','352',null,'Соснівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('50255','UA','16','352',null,'Степанівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59064','UA','24','512',null,'Брусниця');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59065','UA','24','512',null,'Бурдей');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59066','UA','24','512',null,'Валява');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59067','UA','24','512',null,'Верхні Станівці');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59068','UA','24','512',null,'Виноград');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59069','UA','24','512',null,'Витилівка');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59070','UA','24','512',null,'Гаврилівці');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59071','UA','24','512',null,'Глиниця');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59072','UA','24','512',null,'Давидівці');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59073','UA','24','512',null,'Діброва');
INSERT INTO City (id, name, district_id, region_id, country_id) VALUES ('59074','UA','24','512',null,'Драчинці');