TRUNCATE table City;

INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('33466','UA','1','1','Адамівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('33467','UA','1','1','Антонівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('33468','UA','1','1','Балки');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('35383','UA','2','39','Мельниця');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('35384','UA','2','39','Мирин');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('35385','UA','2','39','Мислина');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('35386','UA','2','39','Мощена');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('35387','UA','2','39','Новий Мосир');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('35388','UA','2','39','Нові Кошари');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50245','UA','16','352','Портнівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50246','UA','16','352','Рожаївка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50247','UA','16','352','Розсошенці');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50248','UA','16','352','Рунівщина');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50249','UA','16','352','Сапожине');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50250','UA','16','352','Сем’янівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50251','UA','16','352','Сердюки');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50252','UA','16','352','Снопове');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50253','UA','16','352','Соломахівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50254','UA','16','352','Соснівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('50255','UA','16','352','Степанівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59064','UA','24','512','Брусниця');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59065','UA','24','512','Бурдей');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59066','UA','24','512','Валява');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59067','UA','24','512','Верхні Станівці');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59068','UA','24','512','Виноград');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59069','UA','24','512','Витилівка');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59070','UA','24','512','Гаврилівці');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59071','UA','24','512','Глиниця');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59072','UA','24','512','Давидівці');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59073','UA','24','512','Діброва');
INSERT INTO City (id, country_id, region_id, district_id, name) VALUES ('59074','UA','24','512','Драчинці');
